### ISSUE TITLE
I can't figure out what is wrong with this bisection root search. 

### ISSUE THREAD

**Issue by nmynhier** [nmynhier/HW_3#1]
I have spent hours redoing this code a hundred times and I cannot figure out why I am not getting the correct output. I have tried to match my code exactly to the example in class, yet it is producing a different result!

If you could please help me to identify this i would be very thankful.

@adwasser

**Comment by adwasser** [comment]
responded via email, check the indentation on the last return in the bisection function and also the conditional for updating the bounds
